"""
Daily Brief Tab: Morning Brew Style Intelligence Report

This is the UI for the AI Strategic Intelligence Agent.
It displays the Daily Brief generated by the Sherlock Engine.

The vibe: Newsletter (like Morning Brew), NOT a system alert.
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from typing import Optional, List, Dict

# Import analyst components
try:
    from src.analyst.models import DailyBrief, StrategicNarrative, NarrativeType, ActionUrgency
    from src.analyst.event_stream import transform_to_event_stream, get_event_summary
    from src.analyst.sherlock_engine import run_sherlock_sync
    from src.analyst.world_context import get_world_context, format_world_context_for_llm
    from src.analyst.journal import format_journal_context, save_predictions_from_brief
    ANALYST_AVAILABLE = True
except ImportError as e:
    ANALYST_AVAILABLE = False
    print(f"Analyst module import error: {e}")


def render_daily_brief_tab():
    """Render the Daily Brief tab with Morning Brew style UI."""
    
    # Header
    st.markdown("# 📰 Daily Brief")
    st.caption("Strategic narratives from your AI Analyst • ShelfGuard Intelligence")
    
    if not ANALYST_AVAILABLE:
        st.error("⚠️ Analyst module not available. Check import errors.")
        return
    
    # Check for active project
    active_project_asin = st.session_state.get('active_project_asin', None)
    df_weekly = st.session_state.get('df_weekly', pd.DataFrame())
    
    if not active_project_asin or df_weekly.empty:
        _render_no_project_state()
        return
    
    # Get project info
    project_name = st.session_state.get('active_project_name', 'Your Market')
    target_brand = st.session_state.get('active_brand', '')
    
    # Check if we have a cached brief
    cached_brief = st.session_state.get('daily_brief', None)
    
    col1, col2 = st.columns([3, 1])
    with col1:
        st.markdown(f"**Market:** {project_name}")
        if target_brand:
            st.caption(f"Your Brand: {target_brand}")
    
    with col2:
        if st.button("🔄 Generate New Brief", type="primary", use_container_width=True):
            cached_brief = None
            st.session_state.pop('daily_brief', None)
    
    st.markdown("---")
    
    # Generate or display brief
    if cached_brief is None:
        with st.spinner("🔍 Running Sherlock Analysis... (this takes 30-60 seconds)"):
            brief = _generate_brief(df_weekly, active_project_asin, target_brand)
            if brief:
                st.session_state['daily_brief'] = brief
                cached_brief = brief
    
    if cached_brief:
        _render_daily_brief(cached_brief)
    else:
        st.warning("Could not generate Daily Brief. Check that you have data loaded.")


def _render_no_project_state():
    """Render empty state when no project is active."""
    st.markdown("### 📭 No Market Loaded")
    st.info("Load a market in **Command Center** or **Market Discovery** to generate your Daily Brief.")


def _generate_brief(df_weekly: pd.DataFrame, seed_asin: str, target_brand: str) -> Optional[DailyBrief]:
    """Generate a Daily Brief from the current data."""
    try:
        # Get portfolio ASINs (your products)
        portfolio_asins = []
        if target_brand and 'brand' in df_weekly.columns:
            portfolio_asins = df_weekly[
                df_weekly['brand'].str.lower() == target_brand.lower()
            ]['asin'].unique().tolist()
        
        if not portfolio_asins:
            portfolio_asins = [seed_asin] if seed_asin else []
        
        # Transform to event stream
        st.write("📊 Transforming data to event stream...")
        events = transform_to_event_stream(
            df_weekly=df_weekly,
            portfolio_asins=portfolio_asins,
            category_median_price=df_weekly['buy_box_price'].median() if 'buy_box_price' in df_weekly.columns else 15.0
        )
        
        summary = get_event_summary(events)
        st.write(f"✅ Generated {summary.get('total', 0)} events ({summary.get('portfolio_events', 0)} yours, {summary.get('competitor_events', 0)} competitors)")
        
        if not events:
            st.warning("No significant events detected in the data.")
            return None
        
        # Determine main competitor
        competitor_brand = ""
        if 'brand' in df_weekly.columns and target_brand:
            other_brands = df_weekly[df_weekly['brand'].str.lower() != target_brand.lower()]['brand'].value_counts()
            if len(other_brands) > 0:
                competitor_brand = other_brands.index[0]
        
        # Run Sherlock analysis
        st.write("🔍 Running 5-step Sherlock analysis (Analyst → Skeptic → Editor → Oracle → Red Team)...")
        brief = run_sherlock_sync(
            events=events,
            project_id=seed_asin,
            your_brand=target_brand or "Your Brand",
            competitor_brand=competitor_brand,
            category="deodorant",  # TODO: detect from data
        )
        
        # Save predictions to journal
        if brief and brief.narratives:
            save_predictions_from_brief(seed_asin, brief)
            st.write("📝 Saved predictions to journal for tracking")
        
        return brief
        
    except Exception as e:
        st.error(f"Error generating brief: {e}")
        import traceback
        st.code(traceback.format_exc())
        return None


def _render_daily_brief(brief: DailyBrief):
    """Render the Daily Brief in Morning Brew style."""
    
    # Header section
    st.caption(f"{brief.generated_at.strftime('%A, %B %d, %Y')} • {brief.generated_at.strftime('%I:%M %p')}")
    st.markdown(f"## {brief.market_summary or 'Good Morning. Here is what happened while you slept.'}")
    
    # Metrics row
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Strategic Shifts", len(brief.narratives))
    with col2:
        st.metric("Events Analyzed", f"{brief.event_count:,}")
    with col3:
        st.metric("Ideas Filtered", f"{brief.editor_killed_count} killed")
    with col4:
        st.metric("Opportunity Value", f"+${brief.total_opportunity_value:,.0f}", delta=None)
    
    st.divider()
    
    # Narratives
    for i, narrative in enumerate(brief.narratives, 1):
        _render_narrative(narrative, i)
    
    # Editor's Desk - Show killed ideas (trust building)
    if brief.editor_killed_count > 0 and brief.editor_kill_reasons:
        _render_editor_desk(brief.editor_killed_count, brief.editor_kill_reasons, brief.product_identity)
    
    # Red Team Section
    if brief.red_team_insight:
        st.divider()
        _render_red_team(brief.red_team_insight)
    
    # Journal Context
    if brief.journal_context:
        with st.expander("📓 Journal: Your Prediction History"):
            st.text(brief.journal_context)
    
    # World Context
    if brief.world_context:
        with st.expander("🌍 World Context"):
            st.json(brief.world_context)


def _render_narrative(narrative: StrategicNarrative, index: int):
    """Render a single narrative card."""
    
    # Color and icon by type
    type_styles = {
        NarrativeType.CONQUEST: ("#10b981", "📍", "OPPORTUNITY"),
        NarrativeType.THREAT: ("#ef4444", "⚔️", "THREAT"),
        NarrativeType.OPTIMIZATION: ("#3b82f6", "📈", "OPTIMIZATION"),
        NarrativeType.VULNERABILITY: ("#f59e0b", "🛡️", "VULNERABILITY"),
    }
    
    color, icon, label = type_styles.get(narrative.narrative_type, ("#3b82f6", "📈", "OPTIMIZATION"))
    
    # Urgency badge
    if narrative.action_urgency == ActionUrgency.NOW:
        urgency_html = '<span style="background:#ef4444;color:white;padding:2px 8px;border-radius:4px;font-size:11px;margin-left:10px;">ACT NOW</span>'
    elif narrative.action_urgency == ActionUrgency.THIS_WEEK:
        urgency_html = '<span style="background:#f59e0b;color:white;padding:2px 8px;border-radius:4px;font-size:11px;margin-left:10px;">THIS WEEK</span>'
    else:
        urgency_html = ""
    
    # Impact styling
    impact_color = "#10b981" if narrative.expected_impact >= 0 else "#ef4444"
    impact_str = f"+${abs(narrative.expected_impact):,.0f}" if narrative.expected_impact >= 0 else f"-${abs(narrative.expected_impact):,.0f}"
    
    # Use st.container for proper rendering
    with st.container():
        # Card header with type and impact
        header_cols = st.columns([3, 1])
        with header_cols[0]:
            st.markdown(f"<span style='color:{color};font-weight:600;'>{icon} {label}</span> {urgency_html}", unsafe_allow_html=True)
        with header_cols[1]:
            st.markdown(f"<div style='text-align:right;'><span style='font-size:20px;font-weight:700;color:{impact_color};'>{impact_str}</span><br><span style='font-size:11px;color:#888;'>Expected Impact</span></div>", unsafe_allow_html=True)
        
        # Title
        st.markdown(f"### {narrative.title}")
        
        # Pattern summary
        st.write(narrative.pattern_summary)
        
        # Prediction box
        st.info(f"**PREDICTION:** {narrative.prediction}")
        
        # Confidence and trigger
        meta_cols = st.columns(2)
        with meta_cols[0]:
            st.caption(f"**Confidence:** {narrative.confidence*100:.0f}%")
        with meta_cols[1]:
            st.caption(f"**Watch For:** {narrative.trigger_to_watch}")
        
        # Action section
        st.markdown(f"**Recommended Action:** {narrative.recommended_action}")
        if narrative.action_rationale:
            st.caption(narrative.action_rationale)
        
        # Button
        if narrative.action_urgency == ActionUrgency.NOW:
            st.button("Execute →", key=f"action_{index}", type="primary")
        else:
            st.button("Review →", key=f"action_{index}")
        
        st.divider()


def _render_editor_desk(killed_count: int, kill_reasons: List, product_identity: dict):
    """Render the Editor's Desk section showing killed ideas (trust building)."""
    with st.expander(f"✂️ Editor's Desk: {killed_count} ideas filtered out", expanded=False):
        st.caption("Your AI killed these ideas because they failed quality checks. This shows the AI is self-correcting.")
        
        # Show product identity that was used
        if product_identity:
            st.markdown(f"**Product Identity Used:** {product_identity.get('category', 'Unknown')} | {product_identity.get('brand', 'Unknown')}")
        
        # List the killed ideas
        if kill_reasons:
            for reason in kill_reasons[:10]:  # Max 10 to avoid clutter
                if isinstance(reason, dict):
                    insight_name = reason.get("insight", "Unknown insight")
                    kill_reason = reason.get("reason", "No reason provided")
                    test_failed = reason.get("test_failed", "")
                    
                    # Color code by test failed
                    test_colors = {
                        "RELEVANCE": "#ef4444",  # Red
                        "FEASIBILITY": "#f59e0b",  # Orange
                        "SPECIFICITY": "#3b82f6",  # Blue
                        "TONE": "#8b5cf6",  # Purple
                    }
                    color = test_colors.get(test_failed, "#6b7280")
                    
                    st.markdown(f"""
                    <div style="padding:10px;background:#f8f9fa;border-radius:6px;margin-bottom:8px;border-left:3px solid {color};">
                        <strong>❌ {insight_name}</strong>
                        <br><span style="color:#666;font-size:13px;">{kill_reason}</span>
                        <br><span style="background:{color};color:white;padding:2px 6px;border-radius:3px;font-size:11px;">{test_failed}</span>
                    </div>
                    """, unsafe_allow_html=True)
                else:
                    # Simple string format
                    st.markdown(f"- {reason}")
        else:
            st.info("No kill reasons recorded")


def _render_red_team(insight: str):
    """Render the Red Team vulnerability section."""
    st.markdown("### 🛡️ Red Team Analysis")
    st.caption("What your competitors might be plotting")
    
    # Parse the insight into sections if possible
    with st.container():
        st.warning(insight)
