"""
Daily Brief Tab: Morning Brew Style Intelligence Report

This is the UI for the AI Strategic Intelligence Agent.
It displays the Daily Brief generated by the Sherlock Engine.

The vibe: Newsletter (like Morning Brew), NOT a system alert.
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from typing import Optional, List

# Import analyst components
try:
    from src.analyst.models import DailyBrief, StrategicNarrative, NarrativeType, ActionUrgency
    from src.analyst.event_stream import transform_to_event_stream, get_event_summary
    from src.analyst.sherlock_engine import run_sherlock_sync
    from src.analyst.world_context import get_world_context, format_world_context_for_llm
    from src.analyst.journal import format_journal_context, save_predictions_from_brief
    ANALYST_AVAILABLE = True
except ImportError as e:
    ANALYST_AVAILABLE = False
    print(f"Analyst module import error: {e}")


def render_daily_brief_tab():
    """Render the Daily Brief tab with Morning Brew style UI."""
    
    # Header
    st.markdown("""
    <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #eee; margin-bottom: 30px;">
        <div style="font-size: 14px; letter-spacing: 2px; color: #666; text-transform: uppercase;">
            ShelfGuard Intelligence
        </div>
        <div style="font-size: 36px; font-weight: 800; margin: 10px 0;">
            📰 Daily Brief
        </div>
        <div style="font-size: 14px; color: #888;">
            Strategic narratives from your AI Analyst
        </div>
    </div>
    """, unsafe_allow_html=True)
    
    if not ANALYST_AVAILABLE:
        st.error("⚠️ Analyst module not available. Check import errors.")
        return
    
    # Check for active project
    active_project_asin = st.session_state.get('active_project_asin', None)
    df_weekly = st.session_state.get('df_weekly', pd.DataFrame())
    
    if not active_project_asin or df_weekly.empty:
        _render_no_project_state()
        return
    
    # Get project info
    project_name = st.session_state.get('active_project_name', 'Your Market')
    target_brand = st.session_state.get('active_brand', '')
    
    # Check if we have a cached brief
    cached_brief = st.session_state.get('daily_brief', None)
    
    col1, col2 = st.columns([3, 1])
    with col1:
        st.markdown(f"**Market:** {project_name}")
        if target_brand:
            st.caption(f"Your Brand: {target_brand}")
    
    with col2:
        if st.button("🔄 Generate New Brief", type="primary", use_container_width=True):
            cached_brief = None
            st.session_state.pop('daily_brief', None)
    
    st.markdown("---")
    
    # Generate or display brief
    if cached_brief is None:
        with st.spinner("🔍 Running Sherlock Analysis... (this takes 30-60 seconds)"):
            brief = _generate_brief(df_weekly, active_project_asin, target_brand)
            if brief:
                st.session_state['daily_brief'] = brief
                cached_brief = brief
    
    if cached_brief:
        _render_daily_brief(cached_brief)
    else:
        st.warning("Could not generate Daily Brief. Check that you have data loaded.")


def _render_no_project_state():
    """Render empty state when no project is active."""
    st.markdown("""
    <div style="text-align: center; padding: 60px 40px; background: #f8f9fa; border-radius: 12px;">
        <div style="font-size: 72px; margin-bottom: 20px;">📭</div>
        <div style="font-size: 24px; font-weight: 700; color: #333; margin-bottom: 12px;">
            No Market Loaded
        </div>
        <div style="font-size: 16px; color: #666; margin-bottom: 20px;">
            Load a market in Command Center or Market Discovery to generate your Daily Brief
        </div>
    </div>
    """, unsafe_allow_html=True)


def _generate_brief(df_weekly: pd.DataFrame, seed_asin: str, target_brand: str) -> Optional[DailyBrief]:
    """Generate a Daily Brief from the current data."""
    try:
        # Get portfolio ASINs (your products)
        portfolio_asins = []
        if target_brand and 'brand' in df_weekly.columns:
            portfolio_asins = df_weekly[
                df_weekly['brand'].str.lower() == target_brand.lower()
            ]['asin'].unique().tolist()
        
        if not portfolio_asins:
            portfolio_asins = [seed_asin] if seed_asin else []
        
        # Transform to event stream
        st.write("📊 Transforming data to event stream...")
        events = transform_to_event_stream(
            df_weekly=df_weekly,
            portfolio_asins=portfolio_asins,
            category_median_price=df_weekly['buy_box_price'].median() if 'buy_box_price' in df_weekly.columns else 15.0
        )
        
        summary = get_event_summary(events)
        st.write(f"✅ Generated {summary.get('total', 0)} events ({summary.get('portfolio_events', 0)} yours, {summary.get('competitor_events', 0)} competitors)")
        
        if not events:
            st.warning("No significant events detected in the data.")
            return None
        
        # Determine main competitor
        competitor_brand = ""
        if 'brand' in df_weekly.columns and target_brand:
            other_brands = df_weekly[df_weekly['brand'].str.lower() != target_brand.lower()]['brand'].value_counts()
            if len(other_brands) > 0:
                competitor_brand = other_brands.index[0]
        
        # Run Sherlock analysis
        st.write("🔍 Running 4-step Sherlock analysis...")
        brief = run_sherlock_sync(
            events=events,
            project_id=seed_asin,
            your_brand=target_brand or "Your Brand",
            competitor_brand=competitor_brand,
            category="deodorant",  # TODO: detect from data
        )
        
        # Save predictions to journal
        if brief and brief.narratives:
            save_predictions_from_brief(seed_asin, brief)
            st.write("📝 Saved predictions to journal for tracking")
        
        return brief
        
    except Exception as e:
        st.error(f"Error generating brief: {e}")
        import traceback
        st.code(traceback.format_exc())
        return None


def _render_daily_brief(brief: DailyBrief):
    """Render the Daily Brief in Morning Brew style."""
    
    # Timestamp and summary
    st.markdown(f"""
    <div style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); 
                color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px;">
        <div style="font-size: 12px; text-transform: uppercase; letter-spacing: 2px; opacity: 0.7;">
            {brief.generated_at.strftime('%A, %B %d, %Y')} • {brief.generated_at.strftime('%I:%M %p')}
        </div>
        <div style="font-size: 28px; font-weight: 700; margin: 15px 0;">
            {brief.market_summary or "Good Morning. Here's what happened while you slept."}
        </div>
        <div style="display: flex; gap: 30px; margin-top: 20px;">
            <div>
                <div style="font-size: 24px; font-weight: 700;">{len(brief.narratives)}</div>
                <div style="font-size: 12px; opacity: 0.7;">Strategic Shifts</div>
            </div>
            <div>
                <div style="font-size: 24px; font-weight: 700;">{brief.event_count}</div>
                <div style="font-size: 12px; opacity: 0.7;">Events Analyzed</div>
            </div>
            <div>
                <div style="font-size: 24px; font-weight: 700; color: #4ade80;">+${brief.total_opportunity_value:,.0f}</div>
                <div style="font-size: 12px; opacity: 0.7;">Opportunity Value</div>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)
    
    # Narratives
    for i, narrative in enumerate(brief.narratives, 1):
        _render_narrative(narrative, i)
    
    # Red Team Section
    if brief.red_team_insight:
        st.markdown("---")
        _render_red_team(brief.red_team_insight)
    
    # Journal Context
    if brief.journal_context:
        with st.expander("📓 Journal: Your Prediction History"):
            st.text(brief.journal_context)
    
    # World Context
    if brief.world_context:
        with st.expander("🌍 World Context"):
            st.json(brief.world_context)


def _render_narrative(narrative: StrategicNarrative, index: int):
    """Render a single narrative card."""
    
    # Color and icon by type
    type_config = {
        NarrativeType.CONQUEST: {"icon": "📍", "color": "#10b981", "label": "OPPORTUNITY"},
        NarrativeType.THREAT: {"icon": "⚔️", "color": "#ef4444", "label": "THREAT"},
        NarrativeType.OPTIMIZATION: {"icon": "📈", "color": "#3b82f6", "label": "OPTIMIZATION"},
        NarrativeType.VULNERABILITY: {"icon": "🛡️", "color": "#f59e0b", "label": "VULNERABILITY"},
    }
    
    config = type_config.get(narrative.narrative_type, type_config[NarrativeType.OPTIMIZATION])
    
    urgency_badge = ""
    if narrative.action_urgency == ActionUrgency.NOW:
        urgency_badge = '<span style="background: #ef4444; color: white; padding: 2px 8px; border-radius: 4px; font-size: 11px; margin-left: 10px;">ACT NOW</span>'
    elif narrative.action_urgency == ActionUrgency.THIS_WEEK:
        urgency_badge = '<span style="background: #f59e0b; color: white; padding: 2px 8px; border-radius: 4px; font-size: 11px; margin-left: 10px;">THIS WEEK</span>'
    
    impact_color = "#10b981" if narrative.expected_impact >= 0 else "#ef4444"
    impact_sign = "+" if narrative.expected_impact >= 0 else ""
    
    st.markdown(f"""
    <div style="border-left: 4px solid {config['color']}; padding: 20px 25px; 
                background: white; margin-bottom: 20px; border-radius: 0 8px 8px 0;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
        <div style="display: flex; justify-content: space-between; align-items: flex-start;">
            <div>
                <span style="font-size: 12px; color: {config['color']}; font-weight: 600;">
                    {config['icon']} {config['label']}
                </span>
                {urgency_badge}
            </div>
            <div style="text-align: right;">
                <div style="font-size: 20px; font-weight: 700; color: {impact_color};">
                    {impact_sign}${abs(narrative.expected_impact):,.0f}
                </div>
                <div style="font-size: 11px; color: #888;">Expected Impact</div>
            </div>
        </div>
        
        <div style="font-size: 22px; font-weight: 700; margin: 15px 0 10px 0;">
            {narrative.title}
        </div>
        
        <div style="color: #444; line-height: 1.6; margin-bottom: 15px;">
            {narrative.pattern_summary}
        </div>
        
        <div style="background: #f8f9fa; padding: 15px; border-radius: 6px; margin-bottom: 15px;">
            <div style="font-size: 12px; color: #666; margin-bottom: 5px;">PREDICTION</div>
            <div style="color: #333;">{narrative.prediction}</div>
        </div>
        
        <div style="display: flex; gap: 20px; font-size: 13px; color: #666;">
            <div>
                <strong>Confidence:</strong> {narrative.confidence*100:.0f}%
            </div>
            <div>
                <strong>Watch For:</strong> {narrative.trigger_to_watch}
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)
    
    # Action button
    col1, col2 = st.columns([3, 1])
    with col1:
        st.markdown(f"**Recommended Action:** {narrative.recommended_action}")
        if narrative.action_rationale:
            st.caption(narrative.action_rationale)
    with col2:
        if narrative.action_urgency == ActionUrgency.NOW:
            st.button(f"Execute →", key=f"action_{index}", type="primary")
        else:
            st.button(f"Review →", key=f"action_{index}")
    
    st.markdown("<br>", unsafe_allow_html=True)


def _render_red_team(insight: str):
    """Render the Red Team vulnerability section."""
    st.markdown(f"""
    <div style="border: 2px dashed #f59e0b; padding: 25px; border-radius: 8px; 
                background: linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%);">
        <div style="display: flex; align-items: center; margin-bottom: 15px;">
            <span style="font-size: 28px; margin-right: 10px;">🛡️</span>
            <div>
                <div style="font-size: 18px; font-weight: 700; color: #92400e;">
                    Red Team Analysis
                </div>
                <div style="font-size: 12px; color: #b45309;">
                    What your competitors might be plotting
                </div>
            </div>
        </div>
        <div style="color: #78350f; line-height: 1.6; white-space: pre-line;">
            {insight}
        </div>
    </div>
    """, unsafe_allow_html=True)
